#!/bin/sh

tmux -f /root/tmux.conf  att -t osp || \
   { tmux -f /root/tmux.conf new -s osp -d
     for i in osp16-director osp16-contlr01 osp16-contlr02 osp16-contlr03 osp16-comphci01 osp16-comphci02 osp16-ocp-mgr osp16-idm-1
     do
       label=`echo $i | sed -n 's/osp16-\(.*\)/\1/p'`
       tmux new-window -n $label
       if [ "$i" = "osp16-director" ]; then
         tmux send-keys -t osp:$label 'ssh stack@director.cwrtech.local' enter
         sleep 1
         tmux send-keys -t osp:$label abc123 enter
         sleep 1
         tmux send-keys -t osp:$label 'sudo su -' C-m \; \
              send-keys -t osp:$label 'while true ; do printf "\0"; sleep 240; done &' C-m
         continue
       fi

       if [ "$i" = "osp16-idm-1" ]; then
         #we go directly from satellite to idm using keys
         tmux send-keys -t osp:$label 'ssh idm.cwrtech.local' enter
         sleep 1
         tmux send-keys -t osp:$label 'while true ; do printf "\0"; sleep 240; done &' C-m
         continue
       fi

       if [ "$i" = "osp16-ocp-mgr" ]; then
         tmux send-keys -t osp:$label 'ssh stack@director.cwrtech.local' enter
         sleep 1
         tmux send-keys -t osp:$label abc123 enter
         sleep 1
         tmux send-keys -t osp:$label 'ssh -i /home/stack/ocp311/ocp311-kp.key.pem  cloud-user@ocp-mgr' C-m \; \
              send-keys -t osp:$label 'set -o vi' C-m \; \
              send-keys -t osp:$label 'while true ; do printf "\0"; sleep 240; done &' C-m
         continue
       fi

       tmux send-keys -t osp:$label 'ssh stack@director.cwrtech.local' enter
       sleep 1
       tmux send-keys -t osp:$label abc123 enter
       sleep 1

       tmux send-keys -t osp:$label "ssh heat-admin@$i" C-m \; \
            send-keys -t osp:$label 'set -o vi' C-m \; \
            send-keys -t osp:$label 'sudo su -' C-m \; \
            send-keys -t osp:$label 'while true ; do printf "\0"; sleep 240; done &' C-m
     done
     tmux att -t osp
   }
